### ISSUE TITLE
Atheros - Shailua's ALXEthernet can provoke crashes

### ISSUE THREAD

**Issue by tkrotoff** [tkrotoff/Gigabyte-GA-Z77-DS3H-rev1.1-Hackintosh#6]
Some people have experienced crashes using this driver.
See comments in thread [Experimental Atheros AR81(31/32/51/52/61/62/71/72) Driver for 10.7/10.8](http://www.insanelymac.com/forum/topic/284119-experimental-atheros-ar813132515261627172-driver-for-107108/).

I had some very rare crashes myself probably related to this driver.

The driver has not been updated since the 2012/11/17 (version 1.0.2).

**Comment by tkrotoff** [comment]
I did not have any crash or problem with AtherosE2200Ethernet for several months.
What is nice is the driver still gets improvements (as of today): https://github.com/Mieze/AtherosE2200Ethernet

**Comment by Cin316** [comment]
Just an FYI, I'm getting the following error in the Console and my ethernet is shutting off after my computer is on for a while:
`Ethernet [AtherosE2200]: Fatal interrupt. Reseting chip. ISR=0x200`
I'm going to try updating to the latest AtherosE2200Ethernet driver [here](https://github.com/Mieze/AtherosE2200Ethernet)

I'm currently running 2.0.1, and will be updating to 2.2.0.  Running OS X 10.11.6 El Capitan.
