### ISSUE TITLE
USB 3 ports don't work?

### ISSUE THREAD

**Issue by tkrotoff** [tkrotoff/Gigabyte-GA-Z77-DS3H-rev1.1-Hackintosh#8]
Yosemite 10.10.1 MultiBeast 7.2 Drivers > Misc > USB 3.0 - Universal, description:

> Zenith432's GenericUSBXHCI.kext to enable USB 3.0. Installs GenericUSBXHCI.kext in /System/Library/Extensions/ and xhcdump in /usr/local/bin. Also enables USB 2.0 on LGA 1156 motherboards that aren't using a DSDT and don't enable Rate Matching Hub in BIOS.

Original project page: [GenericUSBXHCI Open Source USB 3.0 xHC driver for OS X 10.7.5 - 10.9](http://sourceforge.net/projects/genericusbxhci/)

Possible solutions:
- https://github.com/RehabMan/OS-X-Generic-USB3, source: http://www.tonymacx86.com/yosemite-desktop-support/143797-z77x-ud3h-usb3-yosemite-problem.html#post892418

**Comment by jfortier** [comment]
I found removing the Universal driver worked without any special drivers. To remove the kext simply:

    # Removes the kext
    sudo rm /Volumes/[SSD]/System/Library/Extensions/GenericUSBXHCI.kext

    # Tells OS X to reload the kexts
    touch /Volumes/[SSD]/System/Library/Extensions/

Obviously insert the volume name where you installed OS X.

**Comment by tkrotoff** [comment]
Verified: USB 3 ports work out of the box
