### ISSUE TITLE
Full speed fans on wake

### ISSUE THREAD

**Issue by benwa** [tkrotoff/Gigabyte-GA-Z77-DS3H-rev1.1-Hackintosh#9]
Currently on 10.10.1, when I wake from sleep, my fans are going at full speed.  They're nice and quiet on a cold (or even warm) boot.  This is a clean install over a freshly formatted 10.9.5 that didn't have this problem.  No BIOS changes in between and no DSDT.
Luckily, this is my only issue.  I have USB3, WiFI, Ethernet, Analog & HDMI audio and multiple monitors working perfectly.  Just some damn loud fans for whatever reason.

org.chameleon.Boot.plist:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>GraphicsEnabler</key>
	<string>No</string>
	<key>IGPEnabler</key>
	<string>Yes</string>
	<key>Timeout</key>
	<string>1</string>
	<key>HDEFLayoutID</key>
	<string>03000000</string>
	<key>Graphics Mode</key>
	<string>1920x1080x32@60</string>
	<key>HDAEnabler</key>
	<string>Yes</string>
	<key>GenerateCStates</key>
	<string>Yes</string>
	<key>GeneratePStates</key>
	<string>Yes</string>
	<key>UseKernelCache</key>
	<string>Yes</string>
	<key>Legacy Logo</key>
	<string>Yes</string>
	<key>Kernel Flags</key>
	<string>kext-dev-mode=1</string>
	<key>Preferred Compression</key>
	<string>lzss</string>
</dict>
</plist>
```

**Comment by benwa** [comment]
So I fixed this, and will embrace the shame that will come of it.

I have a water cooler (Corsair H60 to be exact).  While dusting my case this morning I noticed that the CPU header pins weren't all being used.  That is because the pump for the cooler only has 3 pins (it's supposed to run at full speed all the time.  The fan for the radiator however has 4, as it supports PWM.
Turns out my computer didn't like that very much.

After switching the headers between the two, my computer is now both quieter as it is using PWM correctly, and doesn't have a problem with sleep.

**Comment by bestimmaa** [comment]
Thanks for sharing ... I can image a lot of folks being thankful for it! :)

**Comment by peanutismint** [comment]
Hey @benwa, having the same problem on my GA-Z77-D3H. So you just swapped some fan pins to a different header? Can you offer any further description? I don't have a water cooler or anything...

**Comment by benwa** [comment]
The only thing I remember from this was that if your CPU fan header isn't all hooked up, then the mobo will run it at full speed the whole time.  Might want to check over the BIOS settings related to the fans again.
Other than that, I'm running the latest BIOS version, which I think was a beta.

**Comment by peanutismint** [comment]
Ok cool, thanks for that Bennett! Funny, I just did a test of the sleep-wake and not only did it wake without the black screen but no weird fan issue…?! So maybe another fix I applied also solved this weird one… Holding my breath for now! :-)
